Sync to upstream 2020-12-07
ArduPilot/mavlink pull request #164
Opened 2020-12-07 15:21 UTC by amilcarlucas

2020-12-08 22:16 UTC, hamishwillee commented
This all looks non-controversial to me. Most of it comes from direct discussion with ArduPilot team either on PRs or devcall.

2020-12-08 23:22 UTC, peterbarker requested changes
Could we pop out the autotune_enable patch, please?

This is good apart from that.

Two reasons for the autotune thing; the first is that I don't see another implementation.

The second is that @tridge has muttered something about rejigging autotune for Plane in ArduPilot and I'm not sure how that will work (so we might end up not implementing this message ourselves!)

Not to say that we won't take the patch - just it should be done separately.

2020-12-08 23:22 UTC, peterbarker commented on message_definitions/v1.0/ardupilotmega.xml
> -      <entry value="212" name="MAV_CMD_DO_AUTOTUNE_ENABLE" hasLocation="false" isDestination="false">
I don't see PX4 Firmware using this command.

Is there a second user of this command which warrants it being in common?

2020-12-09 00:35 UTC, hamishwillee commented
> Could we pop out the autotune_enable patch, please?

FYI PX4 moved it because they want to have an implementation, and we assumed that ArduPilot already do. Ie not to reinvent the wheel.

2020-12-09 00:46 UTC, peterbarker commented
On Tue, 8 Dec 2020, Hamish Willee wrote:

>       Could we pop out the autotune_enable patch, please?
> 
> FYI PX4 moved it because they want to have an implementation, and we assumed that ArduPilot already do. Ie not to reinvent the wheel.

Yes, we have an implementation - but only in ArduPlane.  And that's slated 
for change in ways yet to be determined.  I've never heard of anyone 
actually using this mavlink message (or mission command equivalent) - we 
have a dedicated mode for autotune which works just like fly-by-wire-A 
except for monitoring the command responses.

Not saying this patch won't be merged, but it should go to a DevCall (I 
won't merge it off my own bat).

2020-12-09 08:04 UTC, amilcarlucas commented
Done.

2020-12-09 09:20 UTC, tridge approved these changes

2020-12-09 09:20 UTC, merged