ardupilotmega.xml: add MAV_CMD_DO_SCRIPTING
ArduPilot/mavlink pull request #200
Opened 2021-02-25 23:07 UTC by IamPete1

Adds a command for use in missions to trigger scripting actions

2021-02-25 23:27 UTC, peterbarker commented on message_definitions/v1.0/ardupilotmega.xml
> +      <entry value="217" name="MAV_CMD_DO_SCRIPTING" hasLocation="false" isDestination="false">
Perhaps 
```suggestion
      <entry value="217" name="MAV_CMD_DO_SEND_SCRIPT_MESSAGE" hasLocation="false" isDestination="false">
```

It bothers me this is broadcast.  But I guess we've no way to distinguish scripts.

2021-02-26 01:12 UTC, IamPete1 commented
Because we only get 12 bytes in AP mission storage we can only do 3 floats.

2021-02-26 01:21 UTC, IamPete1 commented
https://github.com/ArduPilot/ardupilot/pull/16746

2021-02-26 11:51 UTC, amilcarlucas requested changes
It is probably better to move this above the 42000 value

2021-02-26 12:25 UTC, IamPete1 commented
@amilcarlucas if we go above 256 we can only store 10 bytes, so we could then only do two floats. We could do some tricks to store the third float as two `uint16_t`'s but that makes is all more complicated. 

Although it might be worth adding 10 of these in which case we might need to go above 256 in any-case.

2021-02-26 16:07 UTC, amilcarlucas commented
At some point we will run out of < 256 MAV_CMDs

2021-03-15 01:07 UTC, IamPete1 commented
Turns out we can store a extra int16, so this is now a int16 ID and 3 floats

2021-03-17 08:09 UTC, tridge approved these changes

2021-03-17 08:09 UTC, merged