Add mount_mode to MOUNT_STATUS
ArduPilot/mavlink pull request #236
Opened 2022-01-06 23:00 UTC by hendjoshsr71

Partner Request via Discord

This adds mount_mode to the MOUNT_STATUS message as an extension.

2022-01-06 23:33 UTC, peterbarker requested changes
The mode isn't enough to know everything about what the mode is doing.

 Bits we still won't know:
 - whether it is stabilising on rpy
 - where it is pointing for ROI / wpnext / mavlink system ID

Still... this won't preclude adding more things, I guess...

2022-01-06 23:33 UTC, peterbarker commented on message_definitions/v1.0/ardupilotmega.xml
> +      <field name="mount_mode" type="uint8_t" enum="MAV_MOUNT_MODE">Mount operating mode.</field>
```suggestion
      <field type="uint8_t" name="mount_mode" enum="MAV_MOUNT_MODE">Mount operating mode.</field>
```

2022-01-06 23:47 UTC, hendjoshsr71 commented
> 

Agree! Though if we start adding those I wonder if they are better sent out as an additional message instead of with mode_status? Since they will likely not change as often?

I'm happy to add more fields too but need guidance from users of the message and gimbals.

2022-01-10 23:02 UTC, tridge approved these changes

2022-01-10 23:03 UTC, peterbarker approved these changes

2022-01-10 23:03 UTC, merged

2022-01-11 00:28 UTC, hendjoshsr71 commented
Created a companion PR for this to the upstream MAVLINK:  https://github.com/mavlink/mavlink/pull/1777