update dialects up-to-20220216
ArduPilot/mavlink pull request #248
Opened 2022-02-16 20:55 UTC by amilcarlucas

2022-03-14 23:02 UTC, tridge requested changes

2022-03-14 23:02 UTC, tridge commented on message_definitions/v1.0/AVSSUAS.xml
> +  <include>../../message_definitions/v1.0/common.xml</include>
if this has since been reverted we shouldn't apply it

2022-03-23 23:51 UTC, peterbarker commented
I've made some of these changes in https://github.com/ArduPilot/mavlink/pull/270

I'll need to consider minimal.xml and development.xml changes separately.

The uAvionix messages in our repo should probably go upstream.

2022-04-04 23:33 UTC, amilcarlucas commented
I will rebase this soonish.

2022-04-27 11:34 UTC, peterbarker approved these changes
LGTM

2022-04-27 11:34 UTC, peterbarker commented on message_definitions/v1.0/minimal.xml
> +      <entry value="181" name="MAV_COMP_ID_BATTERY2">
I really don't get why we're bothering to name components.  There are just too great a variety/count of devices out there....

e.g. ArduPilot supports 9 batteries, each of which could be mavlink, and each of which ArduPilot could theoretically handle messages for...

2022-05-02 23:05 UTC, merged